services:
   annex:
      container_name: annex__dev
      build:
         context: .
         dockerfile: ./docker/annex/dockerfile
      image: oktarintentakel/annex
      volumes:
         - .:/project
      ports:
         - 3000:3000
         - 3001:3001
      working_dir: /project
      environment:
         - TERM=xterm-256color
         - LANG=C.UTF-8
         - NODE_ENV=development
      command: bash -c "yarn run examples"
