version: "3"

services:
   annex:
      container_name: annex__dev
      build:
         context: .
         dockerfile: ./docker/annex/dockerfile
      image: oktarintentakel/annex
      volumes:
         - .:/project
      ports:
         - 3000:3000
         - 3001:3001
      working_dir: /project
      environment:
         - TERM=xterm-256color
         - YARN_CACHE_FOLDER=/tmp
      command: bash -c "yarn install; gulp --color examples"
