FROM node:14

ENV TERM=xterm-256color

RUN apt-get update
RUN apt-get upgrade -y

# RUN apt-get install -y wget rsync nano

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /project

RUN yarn global add gulp-cli@2.3.0
RUN yarn global add jsdoc@3.6.6

COPY docker/bash/bashrc /root/.bashrc

EXPOSE 3000
EXPOSE 3001
